osx_image: xcode9.4
language: swift
xcode_workspace: WeightTracker.xcworkspace
xcode_scheme: WeightTrackerTests
podfile: Podfile

script:
    xcodebuild test -sdk iphonesimulator -workspace WeightTracker.xcworkspace -scheme WeightTracker -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' | xcpretty -f `xcpretty-travis-formatter`